[workspace]
resolver = "2"
members = [
    "poodie_runtime",
    "poodie_parser",
    "poodie_routes",
    "poodie_websocket",
    "poodie_env",
    "poodie_server"  # Add this line to include poodie_server
]


# Optional: You can add shared dependencies here as well
