[package]
name = "poodie_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
rusty_v8 = "0.32.1"   # Use the latest available version on crates.io
dotenv = "0.15"
poodie_parser = { path = "../poodie_parser" }
